function Libro1 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LIBRO1 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a string array.
%
%  LIBRO1 = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  Libro1 = importfile("C:\Users\micha\OneDrive - Instituto Tecnologico y de Estudios Superiores de Monterrey\Tercer Semestre\Análisis de métodos matemáticos para la física\Situación problema\Libro1.csv", [1, 5]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Nov-2020 19:06:32

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "nuestraAfliccion";
opts.VariableTypes = "string";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "nuestraAfliccion", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "nuestraAfliccion", "EmptyFieldRule", "auto");

% Import the data
Libro1 = readmatrix(filename, opts);

end